Please put URLs to the libraries you are tallking about:

-   
-

In [ ]:
import sklearn
import numpy as np
import matplotlib.pyplot as plt
import pyspark
from pyspark.mllib.random import RandomRDDs
from pyspark.mllib.feature import Normalizer

In [ ]:
## Constants
N = 200 # train size
M = 100 # test size
D = 2 # dimensinality
T = 2000 # number of rays
one_vs_all = False

assert((not one_vs_all) or N == M)

In [ ]:
train_data = RandomRDDs.normalVectorRDD(sc, N, D)
if one_vs_all:
  test_data = train_data
else:
  test_data = RandomRDDs.normalVectorRDD(sc, M, D)
  
train_data = train_data.zipWithIndex()
test_data = test_data.zipWithIndex()

In [ ]:
def get_uni_sphere():
  u = RandomRDDs.normalVectorRDD(sc, T, D)
  u = Normalizer().transform(u)
  return u
  
rays = get_uni_sphere()

In [ ]:
train_data.cartesian(test_data).collect()

  

>     Out[42]: [((array([ 0.29568958, -0.53991772]), 0),
>       (array([-2.01286931, -0.86136956]), 0)),
>      ((array([ 0.29568958, -0.53991772]), 0),
>       (array([ 0.84229231,  0.46421809]), 1)),
>      ((array([ 0.29568958, -0.53991772]), 0),
>       (array([-0.42803776, -0.58165982]), 2)),
>      ((array([ 0.29568958, -0.53991772]), 0),
>       (array([ 0.31845084,  1.68336195]), 3)),
>      ((array([ 0.29568958, -0.53991772]), 0),
>       (array([-0.45367282, -1.12400269]), 4)),
>      ((array([ 0.29568958, -0.53991772]), 0),
>       (array([-0.07548983, -0.64540421]), 5)),
>      ((array([ 0.29568958, -0.53991772]), 0),
>       (array([-1.38149315, -0.95271764]), 6)),
>      ((array([ 0.29568958, -0.53991772]), 0),
>       (array([-0.18248352, -1.0879801 ]), 7)),
>      ((array([ 0.29568958, -0.53991772]), 0),
>       (array([ 0.4783354 ,  0.62931264]), 8)),
>      ((array([ 0.29568958, -0.53991772]), 0),
>       (array([ 1.87226603, -0.63401282]), 9)),
>      ((array([ 0.29568958, -0.53991772]), 0),
>       (array([-1.12251757,  0.31335918]), 10)),
>      ((array([ 0.29568958, -0.53991772]), 0),
>       (array([ 0.30660537, -0.63915781]), 11)),
>      ((array([ 1.74195034,  0.59257843]), 1),
>       (array([-2.01286931, -0.86136956]), 0)),
>      ((array([-0.41990178,  1.01312245]), 2),
>       (array([-2.01286931, -0.86136956]), 0)),
>      ((array([ 1.74195034,  0.59257843]), 1),
>       (array([ 0.84229231,  0.46421809]), 1)),
>      ((array([ 1.74195034,  0.59257843]), 1),
>       (array([-0.42803776, -0.58165982]), 2)),
>      ((array([-0.41990178,  1.01312245]), 2),
>       (array([ 0.84229231,  0.46421809]), 1)),
>      ((array([-0.41990178,  1.01312245]), 2),
>       (array([-0.42803776, -0.58165982]), 2)),
>      ((array([ 1.74195034,  0.59257843]), 1),
>       (array([ 0.31845084,  1.68336195]), 3)),
>      ((array([ 1.74195034,  0.59257843]), 1),
>       (array([-0.45367282, -1.12400269]), 4)),
>      ((array([ 1.74195034,  0.59257843]), 1),
>       (array([-0.07548983, -0.64540421]), 5)),
>      ((array([ 1.74195034,  0.59257843]), 1),
>       (array([-1.38149315, -0.95271764]), 6)),
>      ((array([-0.41990178,  1.01312245]), 2),
>       (array([ 0.31845084,  1.68336195]), 3)),
>      ((array([-0.41990178,  1.01312245]), 2),
>       (array([-0.45367282, -1.12400269]), 4)),
>      ((array([-0.41990178,  1.01312245]), 2),
>       (array([-0.07548983, -0.64540421]), 5)),
>      ((array([-0.41990178,  1.01312245]), 2),
>       (array([-1.38149315, -0.95271764]), 6)),
>      ((array([ 1.74195034,  0.59257843]), 1),
>       (array([-0.18248352, -1.0879801 ]), 7)),
>      ((array([ 1.74195034,  0.59257843]), 1),
>       (array([ 0.4783354 ,  0.62931264]), 8)),
>      ((array([ 1.74195034,  0.59257843]), 1),
>       (array([ 1.87226603, -0.63401282]), 9)),
>      ((array([ 1.74195034,  0.59257843]), 1),
>       (array([-1.12251757,  0.31335918]), 10)),
>      ((array([ 1.74195034,  0.59257843]), 1),
>       (array([ 0.30660537, -0.63915781]), 11)),
>      ((array([-0.41990178,  1.01312245]), 2),
>       (array([-0.18248352, -1.0879801 ]), 7)),
>      ((array([-0.41990178,  1.01312245]), 2),
>       (array([ 0.4783354 ,  0.62931264]), 8)),
>      ((array([-0.41990178,  1.01312245]), 2),
>       (array([ 1.87226603, -0.63401282]), 9)),
>      ((array([-0.41990178,  1.01312245]), 2),
>       (array([-1.12251757,  0.31335918]), 10)),
>      ((array([-0.41990178,  1.01312245]), 2),
>       (array([ 0.30660537, -0.63915781]), 11)),
>      ((array([ 1.44728983,  0.37634892]), 3),
>       (array([-2.01286931, -0.86136956]), 0)),
>      ((array([ 0.44497839,  0.29831191]), 4),
>       (array([-2.01286931, -0.86136956]), 0)),
>      ((array([-0.51318497, -0.20029463]), 5),
>       (array([-2.01286931, -0.86136956]), 0)),
>      ((array([-0.27315507,  0.57827367]), 6),
>       (array([-2.01286931, -0.86136956]), 0)),
>      ((array([ 1.44728983,  0.37634892]), 3),
>       (array([ 0.84229231,  0.46421809]), 1)),
>      ((array([ 1.44728983,  0.37634892]), 3),
>       (array([-0.42803776, -0.58165982]), 2)),
>      ((array([ 0.44497839,  0.29831191]), 4),
>       (array([ 0.84229231,  0.46421809]), 1)),
>      ((array([ 0.44497839,  0.29831191]), 4),
>       (array([-0.42803776, -0.58165982]), 2)),
>      ((array([-0.51318497, -0.20029463]), 5),
>       (array([ 0.84229231,  0.46421809]), 1)),
>      ((array([-0.51318497, -0.20029463]), 5),
>       (array([-0.42803776, -0.58165982]), 2)),
>      ((array([-0.27315507,  0.57827367]), 6),
>       (array([ 0.84229231,  0.46421809]), 1)),
>      ((array([-0.27315507,  0.57827367]), 6),
>       (array([-0.42803776, -0.58165982]), 2)),
>      ((array([ 1.44728983,  0.37634892]), 3),
>       (array([ 0.31845084,  1.68336195]), 3)),
>      ((array([ 1.44728983,  0.37634892]), 3),
>       (array([-0.45367282, -1.12400269]), 4)),
>      ((array([ 1.44728983,  0.37634892]), 3),
>       (array([-0.07548983, -0.64540421]), 5)),
>      ((array([ 1.44728983,  0.37634892]), 3),
>       (array([-1.38149315, -0.95271764]), 6)),
>      ((array([ 0.44497839,  0.29831191]), 4),
>       (array([ 0.31845084,  1.68336195]), 3)),
>      ((array([ 0.44497839,  0.29831191]), 4),
>       (array([-0.45367282, -1.12400269]), 4)),
>      ((array([ 0.44497839,  0.29831191]), 4),
>       (array([-0.07548983, -0.64540421]), 5)),
>      ((array([ 0.44497839,  0.29831191]), 4),
>       (array([-1.38149315, -0.95271764]), 6)),
>      ((array([-0.51318497, -0.20029463]), 5),
>       (array([ 0.31845084,  1.68336195]), 3)),
>      ((array([-0.51318497, -0.20029463]), 5),
>       (array([-0.45367282, -1.12400269]), 4)),
>      ((array([-0.51318497, -0.20029463]), 5),
>       (array([-0.07548983, -0.64540421]), 5)),
>      ((array([-0.51318497, -0.20029463]), 5),
>       (array([-1.38149315, -0.95271764]), 6)),
>      ((array([-0.27315507,  0.57827367]), 6),
>       (array([ 0.31845084,  1.68336195]), 3)),
>      ((array([-0.27315507,  0.57827367]), 6),
>       (array([-0.45367282, -1.12400269]), 4)),
>      ((array([-0.27315507,  0.57827367]), 6),
>       (array([-0.07548983, -0.64540421]), 5)),
>      ((array([-0.27315507,  0.57827367]), 6),
>       (array([-1.38149315, -0.95271764]), 6)),
>      ((array([ 1.44728983,  0.37634892]), 3),
>       (array([-0.18248352, -1.0879801 ]), 7)),
>      ((array([ 1.44728983,  0.37634892]), 3),
>       (array([ 0.4783354 ,  0.62931264]), 8)),
>      ((array([ 1.44728983,  0.37634892]), 3),
>       (array([ 1.87226603, -0.63401282]), 9)),
>      ((array([ 1.44728983,  0.37634892]), 3),
>       (array([-1.12251757,  0.31335918]), 10)),
>      ((array([ 1.44728983,  0.37634892]), 3),
>       (array([ 0.30660537, -0.63915781]), 11)),
>      ((array([ 0.44497839,  0.29831191]), 4),
>       (array([-0.18248352, -1.0879801 ]), 7)),
>      ((array([ 0.44497839,  0.29831191]), 4),
>       (array([ 0.4783354 ,  0.62931264]), 8)),
>      ((array([ 0.44497839,  0.29831191]), 4),
>       (array([ 1.87226603, -0.63401282]), 9)),
>      ((array([ 0.44497839,  0.29831191]), 4),
>       (array([-1.12251757,  0.31335918]), 10)),
>      ((array([ 0.44497839,  0.29831191]), 4),
>       (array([ 0.30660537, -0.63915781]), 11)),
>      ((array([-0.51318497, -0.20029463]), 5),
>       (array([-0.18248352, -1.0879801 ]), 7)),
>      ((array([-0.51318497, -0.20029463]), 5),
>       (array([ 0.4783354 ,  0.62931264]), 8)),
>      ((array([-0.51318497, -0.20029463]), 5),
>       (array([ 1.87226603, -0.63401282]), 9)),
>      ((array([-0.51318497, -0.20029463]), 5),
>       (array([-1.12251757,  0.31335918]), 10)),
>      ((array([-0.51318497, -0.20029463]), 5),
>       (array([ 0.30660537, -0.63915781]), 11)),
>      ((array([-0.27315507,  0.57827367]), 6),
>       (array([-0.18248352, -1.0879801 ]), 7)),
>      ((array([-0.27315507,  0.57827367]), 6),
>       (array([ 0.4783354 ,  0.62931264]), 8)),
>      ((array([-0.27315507,  0.57827367]), 6),
>       (array([ 1.87226603, -0.63401282]), 9)),
>      ((array([-0.27315507,  0.57827367]), 6),
>       (array([-1.12251757,  0.31335918]), 10)),
>      ((array([-0.27315507,  0.57827367]), 6),
>       (array([ 0.30660537, -0.63915781]), 11)),
>      ((array([-0.34194686, -0.8271094 ]), 7),
>       (array([-2.01286931, -0.86136956]), 0)),
>      ((array([ 1.42457447,  1.10738733]), 8),
>       (array([-2.01286931, -0.86136956]), 0)),
>      ((array([ 0.86049659,  0.94411938]), 9),
>       (array([-2.01286931, -0.86136956]), 0)),
>      ((array([ 0.91121001,  0.94782951]), 10),
>       (array([-2.01286931, -0.86136956]), 0)),
>      ((array([-0.2111352 ,  0.02715169]), 11),
>       (array([-2.01286931, -0.86136956]), 0)),
>      ((array([ 0.45070384, -1.67478689]), 12),
>       (array([-2.01286931, -0.86136956]), 0)),
>      ((array([ 0.62470657,  0.17559647]), 13),
>       (array([-2.01286931, -0.86136956]), 0)),
>      ((array([ 0.91972662, -0.68460849]), 14),
>       (array([-2.01286931, -0.86136956]), 0)),
>      ((array([-0.34194686, -0.8271094 ]), 7),
>       (array([ 0.84229231,  0.46421809]), 1)),
>      ((array([-0.34194686, -0.8271094 ]), 7),
>       (array([-0.42803776, -0.58165982]), 2)),
>      ((array([ 1.42457447,  1.10738733]), 8),
>       (array([ 0.84229231,  0.46421809]), 1)),
>      ((array([ 1.42457447,  1.10738733]), 8),
>       (array([-0.42803776, -0.58165982]), 2)),
>      ((array([ 0.86049659,  0.94411938]), 9),
>       (array([ 0.84229231,  0.46421809]), 1)),
>      ((array([ 0.86049659,  0.94411938]), 9),
>       (array([-0.42803776, -0.58165982]), 2)),
>      ((array([ 0.91121001,  0.94782951]), 10),
>       (array([ 0.84229231,  0.46421809]), 1)),
>      ((array([ 0.91121001,  0.94782951]), 10),
>       (array([-0.42803776, -0.58165982]), 2)),
>      ((array([-0.2111352 ,  0.02715169]), 11),
>       (array([ 0.84229231,  0.46421809]), 1)),
>      ((array([-0.2111352 ,  0.02715169]), 11),
>       (array([-0.42803776, -0.58165982]), 2)),
>      ((array([ 0.45070384, -1.67478689]), 12),
>       (array([ 0.84229231,  0.46421809]), 1)),
>      ((array([ 0.45070384, -1.67478689]), 12),
>       (array([-0.42803776, -0.58165982]), 2)),
>      ((array([ 0.62470657,  0.17559647]), 13),
>       (array([ 0.84229231,  0.46421809]), 1)),
>      ((array([ 0.62470657,  0.17559647]), 13),
>       (array([-0.42803776, -0.58165982]), 2)),
>      ((array([ 0.91972662, -0.68460849]), 14),
>       (array([ 0.84229231,  0.46421809]), 1)),
>      ((array([ 0.91972662, -0.68460849]), 14),
>       (array([-0.42803776, -0.58165982]), 2)),
>      ((array([-0.34194686, -0.8271094 ]), 7),
>       (array([ 0.31845084,  1.68336195]), 3)),
>      ((array([-0.34194686, -0.8271094 ]), 7),
>       (array([-0.45367282, -1.12400269]), 4)),
>      ((array([-0.34194686, -0.8271094 ]), 7),
>       (array([-0.07548983, -0.64540421]), 5)),
>      ((array([-0.34194686, -0.8271094 ]), 7),
>       (array([-1.38149315, -0.95271764]), 6)),
>      ((array([ 1.42457447,  1.10738733]), 8),
>       (array([ 0.31845084,  1.68336195]), 3)),
>      ((array([ 1.42457447,  1.10738733]), 8),
>       (array([-0.45367282, -1.12400269]), 4)),
>      ((array([ 1.42457447,  1.10738733]), 8),
>       (array([-0.07548983, -0.64540421]), 5)),
>      ((array([ 1.42457447,  1.10738733]), 8),
>       (array([-1.38149315, -0.95271764]), 6)),
>      ((array([ 0.86049659,  0.94411938]), 9),
>       (array([ 0.31845084,  1.68336195]), 3)),
>      ((array([ 0.86049659,  0.94411938]), 9),
>       (array([-0.45367282, -1.12400269]), 4)),
>      ((array([ 0.86049659,  0.94411938]), 9),
>       (array([-0.07548983, -0.64540421]), 5)),
>      ((array([ 0.86049659,  0.94411938]), 9),
>       (array([-1.38149315, -0.95271764]), 6)),
>      ((array([ 0.91121001,  0.94782951]), 10),
>       (array([ 0.31845084,  1.68336195]), 3)),
>      ((array([ 0.91121001,  0.94782951]), 10),
>       (array([-0.45367282, -1.12400269]), 4)),
>      ((array([ 0.91121001,  0.94782951]), 10),
>       (array([-0.07548983, -0.64540421]), 5)),
>      ((array([ 0.91121001,  0.94782951]), 10),
>       (array([-1.38149315, -0.95271764]), 6)),
>      ((array([-0.2111352 ,  0.02715169]), 11),
>       (array([ 0.31845084,  1.68336195]), 3)),
>      ((array([-0.2111352 ,  0.02715169]), 11),
>       (array([-0.45367282, -1.12400269]), 4)),
>      ((array([-0.2111352 ,  0.02715169]), 11),
>       (array([-0.07548983, -0.64540421]), 5)),
>      ((array([-0.2111352 ,  0.02715169]), 11),
>       (array([-1.38149315, -0.95271764]), 6)),
>      ((array([ 0.45070384, -1.67478689]), 12),
>       (array([ 0.31845084,  1.68336195]), 3)),
>      ((array([ 0.45070384, -1.67478689]), 12),
>       (array([-0.45367282, -1.12400269]), 4)),
>      ((array([ 0.45070384, -1.67478689]), 12),
>       (array([-0.07548983, -0.64540421]), 5)),
>      ((array([ 0.45070384, -1.67478689]), 12),
>       (array([-1.38149315, -0.95271764]), 6)),
>      ((array([ 0.62470657,  0.17559647]), 13),
>       (array([ 0.31845084,  1.68336195]), 3)),
>      ((array([ 0.62470657,  0.17559647]), 13),
>       (array([-0.45367282, -1.12400269]), 4)),
>      ((array([ 0.62470657,  0.17559647]), 13),
>       (array([-0.07548983, -0.64540421]), 5)),
>      ((array([ 0.62470657,  0.17559647]), 13),
>       (array([-1.38149315, -0.95271764]), 6)),
>      ((array([ 0.91972662, -0.68460849]), 14),
>       (array([ 0.31845084,  1.68336195]), 3)),
>      ((array([ 0.91972662, -0.68460849]), 14),
>       (array([-0.45367282, -1.12400269]), 4)),
>      ((array([ 0.91972662, -0.68460849]), 14),
>       (array([-0.07548983, -0.64540421]), 5)),
>      ((array([ 0.91972662, -0.68460849]), 14),
>       (array([-1.38149315, -0.95271764]), 6)),
>      ((array([-0.34194686, -0.8271094 ]), 7),
>       (array([-0.18248352, -1.0879801 ]), 7)),
>      ((array([-0.34194686, -0.8271094 ]), 7),
>       (array([ 0.4783354 ,  0.62931264]), 8)),
>      ((array([-0.34194686, -0.8271094 ]), 7),
>       (array([ 1.87226603, -0.63401282]), 9)),
>      ((array([-0.34194686, -0.8271094 ]), 7),
>       (array([-1.12251757,  0.31335918]), 10)),
>      ((array([-0.34194686, -0.8271094 ]), 7),
>       (array([ 0.30660537, -0.63915781]), 11)),
>      ((array([ 1.42457447,  1.10738733]), 8),
>       (array([-0.18248352, -1.0879801 ]), 7)),
>      ((array([ 1.42457447,  1.10738733]), 8),
>       (array([ 0.4783354 ,  0.62931264]), 8)),
>      ((array([ 1.42457447,  1.10738733]), 8),
>       (array([ 1.87226603, -0.63401282]), 9)),
>      ((array([ 1.42457447,  1.10738733]), 8),
>       (array([-1.12251757,  0.31335918]), 10)),
>      ((array([ 1.42457447,  1.10738733]), 8),
>       (array([ 0.30660537, -0.63915781]), 11)),
>      ((array([ 0.86049659,  0.94411938]), 9),
>       (array([-0.18248352, -1.0879801 ]), 7)),
>      ((array([ 0.86049659,  0.94411938]), 9),
>       (array([ 0.4783354 ,  0.62931264]), 8)),
>      ((array([ 0.86049659,  0.94411938]), 9),
>       (array([ 1.87226603, -0.63401282]), 9)),
>      ((array([ 0.86049659,  0.94411938]), 9),
>       (array([-1.12251757,  0.31335918]), 10)),
>      ((array([ 0.86049659,  0.94411938]), 9),
>       (array([ 0.30660537, -0.63915781]), 11)),
>      ((array([ 0.91121001,  0.94782951]), 10),
>       (array([-0.18248352, -1.0879801 ]), 7)),
>      ((array([ 0.91121001,  0.94782951]), 10),
>       (array([ 0.4783354 ,  0.62931264]), 8)),
>      ((array([ 0.91121001,  0.94782951]), 10),
>       (array([ 1.87226603, -0.63401282]), 9)),
>      ((array([ 0.91121001,  0.94782951]), 10),
>       (array([-1.12251757,  0.31335918]), 10)),
>      ((array([ 0.91121001,  0.94782951]), 10),
>       (array([ 0.30660537, -0.63915781]), 11)),
>      ((array([-0.2111352 ,  0.02715169]), 11),
>       (array([-0.18248352, -1.0879801 ]), 7)),
>      ((array([-0.2111352 ,  0.02715169]), 11),
>       (array([ 0.4783354 ,  0.62931264]), 8)),
>      ((array([-0.2111352 ,  0.02715169]), 11),
>       (array([ 1.87226603, -0.63401282]), 9)),
>      ((array([-0.2111352 ,  0.02715169]), 11),
>       (array([-1.12251757,  0.31335918]), 10)),
>      ((array([-0.2111352 ,  0.02715169]), 11),
>       (array([ 0.30660537, -0.63915781]), 11)),
>      ((array([ 0.45070384, -1.67478689]), 12),
>       (array([-0.18248352, -1.0879801 ]), 7)),
>      ((array([ 0.45070384, -1.67478689]), 12),
>       (array([ 0.4783354 ,  0.62931264]), 8)),
>      ((array([ 0.45070384, -1.67478689]), 12),
>       (array([ 1.87226603, -0.63401282]), 9)),
>      ((array([ 0.45070384, -1.67478689]), 12),
>       (array([-1.12251757,  0.31335918]), 10)),
>      ((array([ 0.45070384, -1.67478689]), 12),
>       (array([ 0.30660537, -0.63915781]), 11)),
>      ((array([ 0.62470657,  0.17559647]), 13),
>       (array([-0.18248352, -1.0879801 ]), 7)),
>      ((array([ 0.62470657,  0.17559647]), 13),
>       (array([ 0.4783354 ,  0.62931264]), 8)),
>      ((array([ 0.62470657,  0.17559647]), 13),
>       (array([ 1.87226603, -0.63401282]), 9)),
>      ((array([ 0.62470657,  0.17559647]), 13),
>       (array([-1.12251757,  0.31335918]), 10)),
>      ((array([ 0.62470657,  0.17559647]), 13),
>       (array([ 0.30660537, -0.63915781]), 11)),
>      ((array([ 0.91972662, -0.68460849]), 14),
>       (array([-0.18248352, -1.0879801 ]), 7)),
>      ((array([ 0.91972662, -0.68460849]), 14),
>       (array([ 0.4783354 ,  0.62931264]), 8)),
>      ((array([ 0.91972662, -0.68460849]), 14),
>       (array([ 1.87226603, -0.63401282]), 9)),
>      ((array([ 0.91972662, -0.68460849]), 14),
>       (array([-1.12251757,  0.31335918]), 10)),
>      ((array([ 0.91972662, -0.68460849]), 14),
>       (array([ 0.30660537, -0.63915781]), 11)),
>      ((array([-0.34258233,  0.06848227]), 15),
>       (array([-2.01286931, -0.86136956]), 0)),
>      ((array([-1.38846148, -1.65575277]), 16),
>       (array([-2.01286931, -0.86136956]), 0)),
>      ((array([-0.15186608,  0.02084303]), 17),
>       (array([-2.01286931, -0.86136956]), 0)),
>      ((array([ 1.66375393,  0.02557471]), 18),
>       (array([-2.01286931, -0.86136956]), 0)),
>      ((array([ 0.82972518,  1.08894441]), 19),
>       (array([-2.01286931, -0.86136956]), 0)),
>      ((array([ 0.1063126 ,  2.94707398]), 20),
>       (array([-2.01286931, -0.86136956]), 0)),
>      ((array([ 0.78732882, -0.38678061]), 21),
>       (array([-2.01286931, -0.86136956]), 0)),
>      ((array([-1.18819887, -1.15902988]), 22),
>       (array([-2.01286931, -0.86136956]), 0)),
>      ((array([-0.25523505,  1.09684812]), 23),
>       (array([-2.01286931, -0.86136956]), 0)),
>      ((array([ 1.07609456, -0.1921332 ]), 24),
>       (array([-2.01286931, -0.86136956]), 0)),
>      ((array([-0.34258233,  0.06848227]), 15),
>       (array([ 0.84229231,  0.46421809]), 1)),
>      ((array([-0.34258233,  0.06848227]), 15),
>       (array([-0.42803776, -0.58165982]), 2)),
>      ((array([-1.38846148, -1.65575277]), 16),
>       (array([ 0.84229231,  0.46421809]), 1)),
>      ((array([-1.38846148, -1.65575277]), 16),
>       (array([-0.42803776, -0.58165982]), 2)),
>      ((array([-0.15186608,  0.02084303]), 17),
>       (array([ 0.84229231,  0.46421809]), 1)),
>      ((array([-0.15186608,  0.02084303]), 17),
>       (array([-0.42803776, -0.58165982]), 2)),
>      ((array([ 1.66375393,  0.02557471]), 18),
>       (array([ 0.84229231,  0.46421809]), 1)),
>      ((array([ 1.66375393,  0.02557471]), 18),
>       (array([-0.42803776, -0.58165982]), 2)),
>      ((array([ 0.82972518,  1.08894441]), 19),
>       (array([ 0.84229231,  0.46421809]), 1)),
>      ((array([ 0.82972518,  1.08894441]), 19),
>       (array([-0.42803776, -0.58165982]), 2)),
>      ((array([ 0.1063126 ,  2.94707398]), 20),
>       (array([ 0.84229231,  0.46421809]), 1)),
>      ((array([ 0.1063126 ,  2.94707398]), 20),
>       (array([-0.42803776, -0.58165982]), 2)),
>      ((array([ 0.78732882, -0.38678061]), 21),
>       (array([ 0.84229231,  0.46421809]), 1)),
>      ((array([ 0.78732882, -0.38678061]), 21),
>       (array([-0.42803776, -0.58165982]), 2)),
>      ((array([-1.18819887, -1.15902988]), 22),
>       (array([ 0.84229231,  0.46421809]), 1)),
>      ((array([-1.18819887, -1.15902988]), 22),
>       (array([-0.42803776, -0.58165982]), 2)),
>      ((array([-0.25523505,  1.09684812]), 23),
>       (array([ 0.84229231,  0.46421809]), 1)),
>      ((array([-0.25523505,  1.09684812]), 23),
>       (array([-0.42803776, -0.58165982]), 2)),
>      ((array([ 1.07609456, -0.1921332 ]), 24),
>       (array([ 0.84229231,  0.46421809]), 1)),
>      ((array([ 1.07609456, -0.1921332 ]), 24),
>       (array([-0.42803776, -0.58165982]), 2)),
>      ((array([-0.34258233,  0.06848227]), 15),
>       (array([ 0.31845084,  1.68336195]), 3)),
>      ((array([-0.34258233,  0.06848227]), 15),
>       (array([-0.45367282, -1.12400269]), 4)),
>      ((array([-0.34258233,  0.06848227]), 15),
>       (array([-0.07548983, -0.64540421]), 5)),
>      ((array([-0.34258233,  0.06848227]), 15),
>       (array([-1.38149315, -0.95271764]), 6)),
>      ((array([-1.38846148, -1.65575277]), 16),
>       (array([ 0.31845084,  1.68336195]), 3)),
>      ((array([-1.38846148, -1.65575277]), 16),
>       (array([-0.45367282, -1.12400269]), 4)),
>      ((array([-1.38846148, -1.65575277]), 16),
>       (array([-0.07548983, -0.64540421]), 5)),
>      ((array([-1.38846148, -1.65575277]), 16),
>       (array([-1.38149315, -0.95271764]), 6)),
>      ((array([-0.15186608,  0.02084303]), 17),
>       (array([ 0.31845084,  1.68336195]), 3)),
>      ((array([-0.15186608,  0.02084303]), 17),
>       (array([-0.45367282, -1.12400269]), 4)),
>      ((array([-0.15186608,  0.02084303]), 17),
>       (array([-0.07548983, -0.64540421]), 5)),
>      ((array([-0.15186608,  0.02084303]), 17),
>       (array([-1.38149315, -0.95271764]), 6)),
>      ((array([ 1.66375393,  0.02557471]), 18),
>       (array([ 0.31845084,  1.68336195]), 3)),
>      ((array([ 1.66375393,  0.02557471]), 18),
>       (array([-0.45367282, -1.12400269]), 4)),
>      ((array([ 1.66375393,  0.02557471]), 18),
>       (array([-0.07548983, -0.64540421]), 5)),
>      ((array([ 1.66375393,  0.02557471]), 18),
>       (array([-1.38149315, -0.95271764]), 6)),
>      ((array([ 0.82972518,  1.08894441]), 19),
>       (array([ 0.31845084,  1.68336195]), 3)),
>      ((array([ 0.82972518,  1.08894441]), 19),
>       (array([-0.45367282, -1.12400269]), 4)),
>      ((array([ 0.82972518,  1.08894441]), 19),
>       (array([-0.07548983, -0.64540421]), 5)),
>      ((array([ 0.82972518,  1.08894441]), 19),
>       (array([-1.38149315, -0.95271764]), 6)),
>      ((array([ 0.1063126 ,  2.94707398]), 20),
>       (array([ 0.31845084,  1.68336195]), 3)),
>      ((array([ 0.1063126 ,  2.94707398]), 20),
>       (array([-0.45367282, -1.12400269]), 4)),
>      ((array([ 0.1063126 ,  2.94707398]), 20),
>       (array([-0.07548983, -0.64540421]), 5)),
>      ((array([ 0.1063126 ,  2.94707398]), 20),
>       (array([-1.38149315, -0.95271764]), 6)),
>      ((array([ 0.78732882, -0.38678061]), 21),
>       (array([ 0.31845084,  1.68336195]), 3)),
>      ((array([ 0.78732882, -0.38678061]), 21),
>       (array([-0.45367282, -1.12400269]), 4)),
>      ((array([ 0.78732882, -0.38678061]), 21),
>       (array([-0.07548983, -0.64540421]), 5)),
>      ((array([ 0.78732882, -0.38678061]), 21),
>       (array([-1.38149315, -0.95271764]), 6)),
>      ((array([-1.18819887, -1.15902988]), 22),
>       (array([ 0.31845084,  1.68336195]), 3)),
>      ((array([-1.18819887, -1.15902988]), 22),
>       (array([-0.45367282, -1.12400269]), 4)),
>      ((array([-1.18819887, -1.15902988]), 22),
>       (array([-0.07548983, -0.64540421]), 5)),
>      ((array([-1.18819887, -1.15902988]), 22),
>       (array([-1.38149315, -0.95271764]), 6)),
>      ((array([-0.25523505,  1.09684812]), 23),
>       (array([ 0.31845084,  1.68336195]), 3)),
>      ((array([-0.25523505,  1.09684812]), 23),
>       (array([-0.45367282, -1.12400269]), 4)),
>      ((array([-0.25523505,  1.09684812]), 23),
>       (array([-0.07548983, -0.64540421]), 5)),
>      ((array([-0.25523505,  1.09684812]), 23),
>       (array([-1.38149315, -0.95271764]), 6)),
>      ((array([ 1.07609456, -0.1921332 ]), 24),
>       (array([ 0.31845084,  1.68336195]), 3)),
>      ((array([ 1.07609456, -0.1921332 ]), 24),
>       (array([-0.45367282, -1.12400269]), 4)),
>      ((array([ 1.07609456, -0.1921332 ]), 24),
>       (array([-0.07548983, -0.64540421]), 5)),
>      ((array([ 1.07609456, -0.1921332 ]), 24),
>       (array([-1.38149315, -0.95271764]), 6)),
>      ((array([-0.34258233,  0.06848227]), 15),
>       (array([-0.18248352, -1.0879801 ]), 7)),
>      ((array([-0.34258233,  0.06848227]), 15),
>       (array([ 0.4783354 ,  0.62931264]), 8)),
>      ((array([-0.34258233,  0.06848227]), 15),
>       (array([ 1.87226603, -0.63401282]), 9)),
>      ((array([-0.34258233,  0.06848227]), 15),
>       (array([-1.12251757,  0.31335918]), 10)),
>      ((array([-0.34258233,  0.06848227]), 15),
>       (array([ 0.30660537, -0.63915781]), 11)),
>      ((array([-1.38846148, -1.65575277]), 16),
>       (array([-0.18248352, -1.0879801 ]), 7)),
>      ((array([-1.38846148, -1.65575277]), 16),
>       (array([ 0.4783354 ,  0.62931264]), 8)),
>      ((array([-1.38846148, -1.65575277]), 16),
>       (array([ 1.87226603, -0.63401282]), 9)),
>      ((array([-1.38846148, -1.65575277]), 16),
>       (array([-1.12251757,  0.31335918]), 10)),
>      ((array([-1.38846148, -1.65575277]), 16),
>       (array([ 0.30660537, -0.63915781]), 11)),
>      ((array([-0.15186608,  0.02084303]), 17),
>       (array([-0.18248352, -1.0879801 ]), 7)),
>      ((array([-0.15186608,  0.02084303]), 17),
>       (array([ 0.4783354 ,  0.62931264]), 8)),
>      ((array([-0.15186608,  0.02084303]), 17),
>       (array([ 1.87226603, -0.63401282]), 9)),
>      ((array([-0.15186608,  0.02084303]), 17),
>       (array([-1.12251757,  0.31335918]), 10)),
>      ((array([-0.15186608,  0.02084303]), 17),
>       (array([ 0.30660537, -0.63915781]), 11)),
>      ((array([ 1.66375393,  0.02557471]), 18),
>       (array([-0.18248352, -1.0879801 ]), 7)),
>      ((array([ 1.66375393,  0.02557471]), 18),
>       (array([ 0.4783354 ,  0.62931264]), 8)),
>      ((array([ 1.66375393,  0.02557471]), 18),
>       (array([ 1.87226603, -0.63401282]), 9)),
>      ((array([ 1.66375393,  0.02557471]), 18),
>       (array([-1.12251757,  0.31335918]), 10)),
>      ((array([ 1.66375393,  0.02557471]), 18),
>       (array([ 0.30660537, -0.63915781]), 11)),
>      ((array([ 0.82972518,  1.08894441]), 19),
>       (array([-0.18248352, -1.0879801 ]), 7)),
>      ((array([ 0.82972518,  1.08894441]), 19),
>       (array([ 0.4783354 ,  0.62931264]), 8)),
>      ((array([ 0.82972518,  1.08894441]), 19),
>       (array([ 1.87226603, -0.63401282]), 9)),
>      ((array([ 0.82972518,  1.08894441]), 19),
>       (array([-1.12251757,  0.31335918]), 10)),
>      ((array([ 0.82972518,  1.08894441]), 19),
>       (array([ 0.30660537, -0.63915781]), 11)),
>      ((array([ 0.1063126 ,  2.94707398]), 20),
>       (array([-0.18248352, -1.0879801 ]), 7)),
>      ((array([ 0.1063126 ,  2.94707398]), 20),
>       (array([ 0.4783354 ,  0.62931264]), 8)),
>      ((array([ 0.1063126 ,  2.94707398]), 20),
>       (array([ 1.87226603, -0.63401282]), 9)),
>      ((array([ 0.1063126 ,  2.94707398]), 20),
>       (array([-1.12251757,  0.31335918]), 10)),
>      ((array([ 0.1063126 ,  2.94707398]), 20),
>       (array([ 0.30660537, -0.63915781]), 11)),
>      ((array([ 0.78732882, -0.38678061]), 21),
>       (array([-0.18248352, -1.0879801 ]), 7)),
>      ((array([ 0.78732882, -0.38678061]), 21),
>       (array([ 0.4783354 ,  0.62931264]), 8)),
>      ((array([ 0.78732882, -0.38678061]), 21),
>       (array([ 1.87226603, -0.63401282]), 9)),
>      ((array([ 0.78732882, -0.38678061]), 21),
>       (array([-1.12251757,  0.31335918]), 10)),
>      ((array([ 0.78732882, -0.38678061]), 21),
>       (array([ 0.30660537, -0.63915781]), 11)),
>      ((array([-1.18819887, -1.15902988]), 22),
>       (array([-0.18248352, -1.0879801 ]), 7)),
>      ((array([-1.18819887, -1.15902988]), 22),
>       (array([ 0.4783354 ,  0.62931264]), 8)),
>      ((array([-1.18819887, -1.15902988]), 22),
>       (array([ 1.87226603, -0.63401282]), 9)),
>      ((array([-1.18819887, -1.15902988]), 22),
>       (array([-1.12251757,  0.31335918]), 10)),
>      ((array([-1.18819887, -1.15902988]), 22),
>       (array([ 0.30660537, -0.63915781]), 11)),
>      ((array([-0.25523505,  1.09684812]), 23),
>       (array([-0.18248352, -1.0879801 ]), 7)),
>      ((array([-0.25523505,  1.09684812]), 23),
>
>     *** WARNING: skipped 36318 bytes of output ***
>
>       (array([-1.04575568, -0.97934452]), 25)),
>      ((array([ 0.91121001,  0.94782951]), 10),
>       (array([-1.04575568, -0.97934452]), 25)),
>      ((array([-0.2111352 ,  0.02715169]), 11),
>       (array([-1.04575568, -0.97934452]), 25)),
>      ((array([ 0.45070384, -1.67478689]), 12),
>       (array([-1.04575568, -0.97934452]), 25)),
>      ((array([ 0.62470657,  0.17559647]), 13),
>       (array([-1.04575568, -0.97934452]), 25)),
>      ((array([ 0.91972662, -0.68460849]), 14),
>       (array([-1.04575568, -0.97934452]), 25)),
>      ((array([-0.34194686, -0.8271094 ]), 7),
>       (array([-0.12374901, -1.32346456]), 26)),
>      ((array([-0.34194686, -0.8271094 ]), 7),
>       (array([ 1.46998696, -1.68628326]), 27)),
>      ((array([ 1.42457447,  1.10738733]), 8),
>       (array([-0.12374901, -1.32346456]), 26)),
>      ((array([ 1.42457447,  1.10738733]), 8),
>       (array([ 1.46998696, -1.68628326]), 27)),
>      ((array([ 0.86049659,  0.94411938]), 9),
>       (array([-0.12374901, -1.32346456]), 26)),
>      ((array([ 0.86049659,  0.94411938]), 9),
>       (array([ 1.46998696, -1.68628326]), 27)),
>      ((array([ 0.91121001,  0.94782951]), 10),
>       (array([-0.12374901, -1.32346456]), 26)),
>      ((array([ 0.91121001,  0.94782951]), 10),
>       (array([ 1.46998696, -1.68628326]), 27)),
>      ((array([-0.2111352 ,  0.02715169]), 11),
>       (array([-0.12374901, -1.32346456]), 26)),
>      ((array([-0.2111352 ,  0.02715169]), 11),
>       (array([ 1.46998696, -1.68628326]), 27)),
>      ((array([ 0.45070384, -1.67478689]), 12),
>       (array([-0.12374901, -1.32346456]), 26)),
>      ((array([ 0.45070384, -1.67478689]), 12),
>       (array([ 1.46998696, -1.68628326]), 27)),
>      ((array([ 0.62470657,  0.17559647]), 13),
>       (array([-0.12374901, -1.32346456]), 26)),
>      ((array([ 0.62470657,  0.17559647]), 13),
>       (array([ 1.46998696, -1.68628326]), 27)),
>      ((array([ 0.91972662, -0.68460849]), 14),
>       (array([-0.12374901, -1.32346456]), 26)),
>      ((array([ 0.91972662, -0.68460849]), 14),
>       (array([ 1.46998696, -1.68628326]), 27)),
>      ((array([-0.34194686, -0.8271094 ]), 7),
>       (array([ 0.86446309,  0.51646904]), 28)),
>      ((array([-0.34194686, -0.8271094 ]), 7),
>       (array([-0.75129731,  0.32717648]), 29)),
>      ((array([-0.34194686, -0.8271094 ]), 7),
>       (array([ 0.18569954, -0.14219111]), 30)),
>      ((array([-0.34194686, -0.8271094 ]), 7),
>       (array([-0.03068254, -1.19208648]), 31)),
>      ((array([ 1.42457447,  1.10738733]), 8),
>       (array([ 0.86446309,  0.51646904]), 28)),
>      ((array([ 1.42457447,  1.10738733]), 8),
>       (array([-0.75129731,  0.32717648]), 29)),
>      ((array([ 1.42457447,  1.10738733]), 8),
>       (array([ 0.18569954, -0.14219111]), 30)),
>      ((array([ 1.42457447,  1.10738733]), 8),
>       (array([-0.03068254, -1.19208648]), 31)),
>      ((array([ 0.86049659,  0.94411938]), 9),
>       (array([ 0.86446309,  0.51646904]), 28)),
>      ((array([ 0.86049659,  0.94411938]), 9),
>       (array([-0.75129731,  0.32717648]), 29)),
>      ((array([ 0.86049659,  0.94411938]), 9),
>       (array([ 0.18569954, -0.14219111]), 30)),
>      ((array([ 0.86049659,  0.94411938]), 9),
>       (array([-0.03068254, -1.19208648]), 31)),
>      ((array([ 0.91121001,  0.94782951]), 10),
>       (array([ 0.86446309,  0.51646904]), 28)),
>      ((array([ 0.91121001,  0.94782951]), 10),
>       (array([-0.75129731,  0.32717648]), 29)),
>      ((array([ 0.91121001,  0.94782951]), 10),
>       (array([ 0.18569954, -0.14219111]), 30)),
>      ((array([ 0.91121001,  0.94782951]), 10),
>       (array([-0.03068254, -1.19208648]), 31)),
>      ((array([-0.2111352 ,  0.02715169]), 11),
>       (array([ 0.86446309,  0.51646904]), 28)),
>      ((array([-0.2111352 ,  0.02715169]), 11),
>       (array([-0.75129731,  0.32717648]), 29)),
>      ((array([-0.2111352 ,  0.02715169]), 11),
>       (array([ 0.18569954, -0.14219111]), 30)),
>      ((array([-0.2111352 ,  0.02715169]), 11),
>       (array([-0.03068254, -1.19208648]), 31)),
>      ((array([ 0.45070384, -1.67478689]), 12),
>       (array([ 0.86446309,  0.51646904]), 28)),
>      ((array([ 0.45070384, -1.67478689]), 12),
>       (array([-0.75129731,  0.32717648]), 29)),
>      ((array([ 0.45070384, -1.67478689]), 12),
>       (array([ 0.18569954, -0.14219111]), 30)),
>      ((array([ 0.45070384, -1.67478689]), 12),
>       (array([-0.03068254, -1.19208648]), 31)),
>      ((array([ 0.62470657,  0.17559647]), 13),
>       (array([ 0.86446309,  0.51646904]), 28)),
>      ((array([ 0.62470657,  0.17559647]), 13),
>       (array([-0.75129731,  0.32717648]), 29)),
>      ((array([ 0.62470657,  0.17559647]), 13),
>       (array([ 0.18569954, -0.14219111]), 30)),
>      ((array([ 0.62470657,  0.17559647]), 13),
>       (array([-0.03068254, -1.19208648]), 31)),
>      ((array([ 0.91972662, -0.68460849]), 14),
>       (array([ 0.86446309,  0.51646904]), 28)),
>      ((array([ 0.91972662, -0.68460849]), 14),
>       (array([-0.75129731,  0.32717648]), 29)),
>      ((array([ 0.91972662, -0.68460849]), 14),
>       (array([ 0.18569954, -0.14219111]), 30)),
>      ((array([ 0.91972662, -0.68460849]), 14),
>       (array([-0.03068254, -1.19208648]), 31)),
>      ((array([-0.34194686, -0.8271094 ]), 7),
>       (array([-0.12907439,  0.54689162]), 32)),
>      ((array([-0.34194686, -0.8271094 ]), 7),
>       (array([ 0.92282485, -0.05957153]), 33)),
>      ((array([-0.34194686, -0.8271094 ]), 7),
>       (array([ 1.91918518, -0.72625098]), 34)),
>      ((array([-0.34194686, -0.8271094 ]), 7),
>       (array([-1.22144875, -0.45763661]), 35)),
>      ((array([-0.34194686, -0.8271094 ]), 7),
>       (array([ 0.21274076, -0.8581371 ]), 36)),
>      ((array([ 1.42457447,  1.10738733]), 8),
>       (array([-0.12907439,  0.54689162]), 32)),
>      ((array([ 1.42457447,  1.10738733]), 8),
>       (array([ 0.92282485, -0.05957153]), 33)),
>      ((array([ 1.42457447,  1.10738733]), 8),
>       (array([ 1.91918518, -0.72625098]), 34)),
>      ((array([ 1.42457447,  1.10738733]), 8),
>       (array([-1.22144875, -0.45763661]), 35)),
>      ((array([ 1.42457447,  1.10738733]), 8),
>       (array([ 0.21274076, -0.8581371 ]), 36)),
>      ((array([ 0.86049659,  0.94411938]), 9),
>       (array([-0.12907439,  0.54689162]), 32)),
>      ((array([ 0.86049659,  0.94411938]), 9),
>       (array([ 0.92282485, -0.05957153]), 33)),
>      ((array([ 0.86049659,  0.94411938]), 9),
>       (array([ 1.91918518, -0.72625098]), 34)),
>      ((array([ 0.86049659,  0.94411938]), 9),
>       (array([-1.22144875, -0.45763661]), 35)),
>      ((array([ 0.86049659,  0.94411938]), 9),
>       (array([ 0.21274076, -0.8581371 ]), 36)),
>      ((array([ 0.91121001,  0.94782951]), 10),
>       (array([-0.12907439,  0.54689162]), 32)),
>      ((array([ 0.91121001,  0.94782951]), 10),
>       (array([ 0.92282485, -0.05957153]), 33)),
>      ((array([ 0.91121001,  0.94782951]), 10),
>       (array([ 1.91918518, -0.72625098]), 34)),
>      ((array([ 0.91121001,  0.94782951]), 10),
>       (array([-1.22144875, -0.45763661]), 35)),
>      ((array([ 0.91121001,  0.94782951]), 10),
>       (array([ 0.21274076, -0.8581371 ]), 36)),
>      ((array([-0.2111352 ,  0.02715169]), 11),
>       (array([-0.12907439,  0.54689162]), 32)),
>      ((array([-0.2111352 ,  0.02715169]), 11),
>       (array([ 0.92282485, -0.05957153]), 33)),
>      ((array([-0.2111352 ,  0.02715169]), 11),
>       (array([ 1.91918518, -0.72625098]), 34)),
>      ((array([-0.2111352 ,  0.02715169]), 11),
>       (array([-1.22144875, -0.45763661]), 35)),
>      ((array([-0.2111352 ,  0.02715169]), 11),
>       (array([ 0.21274076, -0.8581371 ]), 36)),
>      ((array([ 0.45070384, -1.67478689]), 12),
>       (array([-0.12907439,  0.54689162]), 32)),
>      ((array([ 0.45070384, -1.67478689]), 12),
>       (array([ 0.92282485, -0.05957153]), 33)),
>      ((array([ 0.45070384, -1.67478689]), 12),
>       (array([ 1.91918518, -0.72625098]), 34)),
>      ((array([ 0.45070384, -1.67478689]), 12),
>       (array([-1.22144875, -0.45763661]), 35)),
>      ((array([ 0.45070384, -1.67478689]), 12),
>       (array([ 0.21274076, -0.8581371 ]), 36)),
>      ((array([ 0.62470657,  0.17559647]), 13),
>       (array([-0.12907439,  0.54689162]), 32)),
>      ((array([ 0.62470657,  0.17559647]), 13),
>       (array([ 0.92282485, -0.05957153]), 33)),
>      ((array([ 0.62470657,  0.17559647]), 13),
>       (array([ 1.91918518, -0.72625098]), 34)),
>      ((array([ 0.62470657,  0.17559647]), 13),
>       (array([-1.22144875, -0.45763661]), 35)),
>      ((array([ 0.62470657,  0.17559647]), 13),
>       (array([ 0.21274076, -0.8581371 ]), 36)),
>      ((array([ 0.91972662, -0.68460849]), 14),
>       (array([-0.12907439,  0.54689162]), 32)),
>      ((array([ 0.91972662, -0.68460849]), 14),
>       (array([ 0.92282485, -0.05957153]), 33)),
>      ((array([ 0.91972662, -0.68460849]), 14),
>       (array([ 1.91918518, -0.72625098]), 34)),
>      ((array([ 0.91972662, -0.68460849]), 14),
>       (array([-1.22144875, -0.45763661]), 35)),
>      ((array([ 0.91972662, -0.68460849]), 14),
>       (array([ 0.21274076, -0.8581371 ]), 36)),
>      ((array([-0.34258233,  0.06848227]), 15),
>       (array([-1.04575568, -0.97934452]), 25)),
>      ((array([-1.38846148, -1.65575277]), 16),
>       (array([-1.04575568, -0.97934452]), 25)),
>      ((array([-0.15186608,  0.02084303]), 17),
>       (array([-1.04575568, -0.97934452]), 25)),
>      ((array([ 1.66375393,  0.02557471]), 18),
>       (array([-1.04575568, -0.97934452]), 25)),
>      ((array([ 0.82972518,  1.08894441]), 19),
>       (array([-1.04575568, -0.97934452]), 25)),
>      ((array([ 0.1063126 ,  2.94707398]), 20),
>       (array([-1.04575568, -0.97934452]), 25)),
>      ((array([ 0.78732882, -0.38678061]), 21),
>       (array([-1.04575568, -0.97934452]), 25)),
>      ((array([-1.18819887, -1.15902988]), 22),
>       (array([-1.04575568, -0.97934452]), 25)),
>      ((array([-0.25523505,  1.09684812]), 23),
>       (array([-1.04575568, -0.97934452]), 25)),
>      ((array([ 1.07609456, -0.1921332 ]), 24),
>       (array([-1.04575568, -0.97934452]), 25)),
>      ((array([-0.34258233,  0.06848227]), 15),
>       (array([-0.12374901, -1.32346456]), 26)),
>      ((array([-0.34258233,  0.06848227]), 15),
>       (array([ 1.46998696, -1.68628326]), 27)),
>      ((array([-1.38846148, -1.65575277]), 16),
>       (array([-0.12374901, -1.32346456]), 26)),
>      ((array([-1.38846148, -1.65575277]), 16),
>       (array([ 1.46998696, -1.68628326]), 27)),
>      ((array([-0.15186608,  0.02084303]), 17),
>       (array([-0.12374901, -1.32346456]), 26)),
>      ((array([-0.15186608,  0.02084303]), 17),
>       (array([ 1.46998696, -1.68628326]), 27)),
>      ((array([ 1.66375393,  0.02557471]), 18),
>       (array([-0.12374901, -1.32346456]), 26)),
>      ((array([ 1.66375393,  0.02557471]), 18),
>       (array([ 1.46998696, -1.68628326]), 27)),
>      ((array([ 0.82972518,  1.08894441]), 19),
>       (array([-0.12374901, -1.32346456]), 26)),
>      ((array([ 0.82972518,  1.08894441]), 19),
>       (array([ 1.46998696, -1.68628326]), 27)),
>      ((array([ 0.1063126 ,  2.94707398]), 20),
>       (array([-0.12374901, -1.32346456]), 26)),
>      ((array([ 0.1063126 ,  2.94707398]), 20),
>       (array([ 1.46998696, -1.68628326]), 27)),
>      ((array([ 0.78732882, -0.38678061]), 21),
>       (array([-0.12374901, -1.32346456]), 26)),
>      ((array([ 0.78732882, -0.38678061]), 21),
>       (array([ 1.46998696, -1.68628326]), 27)),
>      ((array([-1.18819887, -1.15902988]), 22),
>       (array([-0.12374901, -1.32346456]), 26)),
>      ((array([-1.18819887, -1.15902988]), 22),
>       (array([ 1.46998696, -1.68628326]), 27)),
>      ((array([-0.25523505,  1.09684812]), 23),
>       (array([-0.12374901, -1.32346456]), 26)),
>      ((array([-0.25523505,  1.09684812]), 23),
>       (array([ 1.46998696, -1.68628326]), 27)),
>      ((array([ 1.07609456, -0.1921332 ]), 24),
>       (array([-0.12374901, -1.32346456]), 26)),
>      ((array([ 1.07609456, -0.1921332 ]), 24),
>       (array([ 1.46998696, -1.68628326]), 27)),
>      ((array([-0.34258233,  0.06848227]), 15),
>       (array([ 0.86446309,  0.51646904]), 28)),
>      ((array([-0.34258233,  0.06848227]), 15),
>       (array([-0.75129731,  0.32717648]), 29)),
>      ((array([-0.34258233,  0.06848227]), 15),
>       (array([ 0.18569954, -0.14219111]), 30)),
>      ((array([-0.34258233,  0.06848227]), 15),
>       (array([-0.03068254, -1.19208648]), 31)),
>      ((array([-1.38846148, -1.65575277]), 16),
>       (array([ 0.86446309,  0.51646904]), 28)),
>      ((array([-1.38846148, -1.65575277]), 16),
>       (array([-0.75129731,  0.32717648]), 29)),
>      ((array([-1.38846148, -1.65575277]), 16),
>       (array([ 0.18569954, -0.14219111]), 30)),
>      ((array([-1.38846148, -1.65575277]), 16),
>       (array([-0.03068254, -1.19208648]), 31)),
>      ((array([-0.15186608,  0.02084303]), 17),
>       (array([ 0.86446309,  0.51646904]), 28)),
>      ((array([-0.15186608,  0.02084303]), 17),
>       (array([-0.75129731,  0.32717648]), 29)),
>      ((array([-0.15186608,  0.02084303]), 17),
>       (array([ 0.18569954, -0.14219111]), 30)),
>      ((array([-0.15186608,  0.02084303]), 17),
>       (array([-0.03068254, -1.19208648]), 31)),
>      ((array([ 1.66375393,  0.02557471]), 18),
>       (array([ 0.86446309,  0.51646904]), 28)),
>      ((array([ 1.66375393,  0.02557471]), 18),
>       (array([-0.75129731,  0.32717648]), 29)),
>      ((array([ 1.66375393,  0.02557471]), 18),
>       (array([ 0.18569954, -0.14219111]), 30)),
>      ((array([ 1.66375393,  0.02557471]), 18),
>       (array([-0.03068254, -1.19208648]), 31)),
>      ((array([ 0.82972518,  1.08894441]), 19),
>       (array([ 0.86446309,  0.51646904]), 28)),
>      ((array([ 0.82972518,  1.08894441]), 19),
>       (array([-0.75129731,  0.32717648]), 29)),
>      ((array([ 0.82972518,  1.08894441]), 19),
>       (array([ 0.18569954, -0.14219111]), 30)),
>      ((array([ 0.82972518,  1.08894441]), 19),
>       (array([-0.03068254, -1.19208648]), 31)),
>      ((array([ 0.1063126 ,  2.94707398]), 20),
>       (array([ 0.86446309,  0.51646904]), 28)),
>      ((array([ 0.1063126 ,  2.94707398]), 20),
>       (array([-0.75129731,  0.32717648]), 29)),
>      ((array([ 0.1063126 ,  2.94707398]), 20),
>       (array([ 0.18569954, -0.14219111]), 30)),
>      ((array([ 0.1063126 ,  2.94707398]), 20),
>       (array([-0.03068254, -1.19208648]), 31)),
>      ((array([ 0.78732882, -0.38678061]), 21),
>       (array([ 0.86446309,  0.51646904]), 28)),
>      ((array([ 0.78732882, -0.38678061]), 21),
>       (array([-0.75129731,  0.32717648]), 29)),
>      ((array([ 0.78732882, -0.38678061]), 21),
>       (array([ 0.18569954, -0.14219111]), 30)),
>      ((array([ 0.78732882, -0.38678061]), 21),
>       (array([-0.03068254, -1.19208648]), 31)),
>      ((array([-1.18819887, -1.15902988]), 22),
>       (array([ 0.86446309,  0.51646904]), 28)),
>      ((array([-1.18819887, -1.15902988]), 22),
>       (array([-0.75129731,  0.32717648]), 29)),
>      ((array([-1.18819887, -1.15902988]), 22),
>       (array([ 0.18569954, -0.14219111]), 30)),
>      ((array([-1.18819887, -1.15902988]), 22),
>       (array([-0.03068254, -1.19208648]), 31)),
>      ((array([-0.25523505,  1.09684812]), 23),
>       (array([ 0.86446309,  0.51646904]), 28)),
>      ((array([-0.25523505,  1.09684812]), 23),
>       (array([-0.75129731,  0.32717648]), 29)),
>      ((array([-0.25523505,  1.09684812]), 23),
>       (array([ 0.18569954, -0.14219111]), 30)),
>      ((array([-0.25523505,  1.09684812]), 23),
>       (array([-0.03068254, -1.19208648]), 31)),
>      ((array([ 1.07609456, -0.1921332 ]), 24),
>       (array([ 0.86446309,  0.51646904]), 28)),
>      ((array([ 1.07609456, -0.1921332 ]), 24),
>       (array([-0.75129731,  0.32717648]), 29)),
>      ((array([ 1.07609456, -0.1921332 ]), 24),
>       (array([ 0.18569954, -0.14219111]), 30)),
>      ((array([ 1.07609456, -0.1921332 ]), 24),
>       (array([-0.03068254, -1.19208648]), 31)),
>      ((array([-0.34258233,  0.06848227]), 15),
>       (array([-0.12907439,  0.54689162]), 32)),
>      ((array([-0.34258233,  0.06848227]), 15),
>       (array([ 0.92282485, -0.05957153]), 33)),
>      ((array([-0.34258233,  0.06848227]), 15),
>       (array([ 1.91918518, -0.72625098]), 34)),
>      ((array([-0.34258233,  0.06848227]), 15),
>       (array([-1.22144875, -0.45763661]), 35)),
>      ((array([-0.34258233,  0.06848227]), 15),
>       (array([ 0.21274076, -0.8581371 ]), 36)),
>      ((array([-1.38846148, -1.65575277]), 16),
>       (array([-0.12907439,  0.54689162]), 32)),
>      ((array([-1.38846148, -1.65575277]), 16),
>       (array([ 0.92282485, -0.05957153]), 33)),
>      ((array([-1.38846148, -1.65575277]), 16),
>       (array([ 1.91918518, -0.72625098]), 34)),
>      ((array([-1.38846148, -1.65575277]), 16),
>       (array([-1.22144875, -0.45763661]), 35)),
>      ((array([-1.38846148, -1.65575277]), 16),
>       (array([ 0.21274076, -0.8581371 ]), 36)),
>      ((array([-0.15186608,  0.02084303]), 17),
>       (array([-0.12907439,  0.54689162]), 32)),
>      ((array([-0.15186608,  0.02084303]), 17),
>       (array([ 0.92282485, -0.05957153]), 33)),
>      ((array([-0.15186608,  0.02084303]), 17),
>       (array([ 1.91918518, -0.72625098]), 34)),
>      ((array([-0.15186608,  0.02084303]), 17),
>       (array([-1.22144875, -0.45763661]), 35)),
>      ((array([-0.15186608,  0.02084303]), 17),
>       (array([ 0.21274076, -0.8581371 ]), 36)),
>      ((array([ 1.66375393,  0.02557471]), 18),
>       (array([-0.12907439,  0.54689162]), 32)),
>      ((array([ 1.66375393,  0.02557471]), 18),
>       (array([ 0.92282485, -0.05957153]), 33)),
>      ((array([ 1.66375393,  0.02557471]), 18),
>       (array([ 1.91918518, -0.72625098]), 34)),
>      ((array([ 1.66375393,  0.02557471]), 18),
>       (array([-1.22144875, -0.45763661]), 35)),
>      ((array([ 1.66375393,  0.02557471]), 18),
>       (array([ 0.21274076, -0.8581371 ]), 36)),
>      ((array([ 0.82972518,  1.08894441]), 19),
>       (array([-0.12907439,  0.54689162]), 32)),
>      ((array([ 0.82972518,  1.08894441]), 19),
>       (array([ 0.92282485, -0.05957153]), 33)),
>      ((array([ 0.82972518,  1.08894441]), 19),
>       (array([ 1.91918518, -0.72625098]), 34)),
>      ((array([ 0.82972518,  1.08894441]), 19),
>       (array([-1.22144875, -0.45763661]), 35)),
>      ((array([ 0.82972518,  1.08894441]), 19),
>       (array([ 0.21274076, -0.8581371 ]), 36)),
>      ((array([ 0.1063126 ,  2.94707398]), 20),
>       (array([-0.12907439,  0.54689162]), 32)),
>      ((array([ 0.1063126 ,  2.94707398]), 20),
>       (array([ 0.92282485, -0.05957153]), 33)),
>      ((array([ 0.1063126 ,  2.94707398]), 20),
>       (array([ 1.91918518, -0.72625098]), 34)),
>      ((array([ 0.1063126 ,  2.94707398]), 20),
>       (array([-1.22144875, -0.45763661]), 35)),
>      ((array([ 0.1063126 ,  2.94707398]), 20),
>       (array([ 0.21274076, -0.8581371 ]), 36)),
>      ((array([ 0.78732882, -0.38678061]), 21),
>       (array([-0.12907439,  0.54689162]), 32)),
>      ((array([ 0.78732882, -0.38678061]), 21),
>       (array([ 0.92282485, -0.05957153]), 33)),
>      ((array([ 0.78732882, -0.38678061]), 21),
>       (array([ 1.91918518, -0.72625098]), 34)),
>      ((array([ 0.78732882, -0.38678061]), 21),
>       (array([-1.22144875, -0.45763661]), 35)),
>      ((array([ 0.78732882, -0.38678061]), 21),
>       (array([ 0.21274076, -0.8581371 ]), 36)),
>      ((array([-1.18819887, -1.15902988]), 22),
>       (array([-0.12907439,  0.54689162]), 32)),
>      ((array([-1.18819887, -1.15902988]), 22),
>       (array([ 0.92282485, -0.05957153]), 33)),
>      ((array([-1.18819887, -1.15902988]), 22),
>       (array([ 1.91918518, -0.72625098]), 34)),
>      ((array([-1.18819887, -1.15902988]), 22),
>       (array([-1.22144875, -0.45763661]), 35)),
>      ((array([-1.18819887, -1.15902988]), 22),
>       (array([ 0.21274076, -0.8581371 ]), 36)),
>      ((array([-0.25523505,  1.09684812]), 23),
>       (array([-0.12907439,  0.54689162]), 32)),
>      ((array([-0.25523505,  1.09684812]), 23),
>       (array([ 0.92282485, -0.05957153]), 33)),
>      ((array([-0.25523505,  1.09684812]), 23),
>       (array([ 1.91918518, -0.72625098]), 34)),
>      ((array([-0.25523505,  1.09684812]), 23),
>       (array([-1.22144875, -0.45763661]), 35)),
>      ((array([-0.25523505,  1.09684812]), 23),
>       (array([ 0.21274076, -0.8581371 ]), 36)),
>      ((array([ 1.07609456, -0.1921332 ]), 24),
>       (array([-0.12907439,  0.54689162]), 32)),
>      ((array([ 1.07609456, -0.1921332 ]), 24),
>       (array([ 0.92282485, -0.05957153]), 33)),
>      ((array([ 1.07609456, -0.1921332 ]), 24),
>       (array([ 1.91918518, -0.72625098]), 34)),
>      ((array([ 1.07609456, -0.1921332 ]), 24),
>       (array([-1.22144875, -0.45763661]), 35)),
>      ((array([ 1.07609456, -0.1921332 ]), 24),
>       (array([ 0.21274076, -0.8581371 ]), 36)),
>      ((array([ 0.29568958, -0.53991772]), 0),
>       (array([-0.40769019,  0.26518391]), 37)),
>      ((array([ 0.29568958, -0.53991772]), 0),
>       (array([ 0.29609466,  1.2370943 ]), 38)),
>      ((array([ 0.29568958, -0.53991772]), 0),
>       (array([-0.65231655, -0.36407806]), 39)),
>      ((array([ 0.29568958, -0.53991772]), 0),
>       (array([ 0.06196598,  1.88883008]), 40)),
>      ((array([ 0.29568958, -0.53991772]), 0),
>       (array([ 1.08164892,  0.47925854]), 41)),
>      ((array([ 0.29568958, -0.53991772]), 0),
>       (array([-0.4764733 ,  0.84099526]), 42)),
>      ((array([ 0.29568958, -0.53991772]), 0),
>       (array([-0.7503309,  0.3275802]), 43)),
>      ((array([ 0.29568958, -0.53991772]), 0),
>       (array([ 0.62945922, -0.39004683]), 44)),
>      ((array([ 0.29568958, -0.53991772]), 0),
>       (array([ 0.40821631, -0.64437056]), 45)),
>      ((array([ 0.29568958, -0.53991772]), 0),
>       (array([-0.21032356,  0.19358758]), 46)),
>      ((array([ 0.29568958, -0.53991772]), 0),
>       (array([ 0.82872034,  0.34594806]), 47)),
>      ((array([ 0.29568958, -0.53991772]), 0),
>       (array([ 1.84918398,  1.06022452]), 48)),
>      ((array([ 0.29568958, -0.53991772]), 0),
>       (array([ 1.19255377,  1.24440407]), 49)),
>      ((array([ 1.74195034,  0.59257843]), 1),
>       (array([-0.40769019,  0.26518391]), 37)),
>      ((array([-0.41990178,  1.01312245]), 2),
>       (array([-0.40769019,  0.26518391]), 37)),
>      ((array([ 1.74195034,  0.59257843]), 1),
>       (array([ 0.29609466,  1.2370943 ]), 38)),
>      ((array([ 1.74195034,  0.59257843]), 1),
>       (array([-0.65231655, -0.36407806]), 39)),
>      ((array([-0.41990178,  1.01312245]), 2),
>       (array([ 0.29609466,  1.2370943 ]), 38)),
>      ((array([-0.41990178,  1.01312245]), 2),
>       (array([-0.65231655, -0.36407806]), 39)),
>      ((array([ 1.74195034,  0.59257843]), 1),
>       (array([ 0.06196598,  1.88883008]), 40)),
>      ((array([ 1.74195034,  0.59257843]), 1),
>       (array([ 1.08164892,  0.47925854]), 41)),
>      ((array([ 1.74195034,  0.59257843]), 1),
>       (array([-0.4764733 ,  0.84099526]), 42)),
>      ((array([ 1.74195034,  0.59257843]), 1),
>       (array([-0.7503309,  0.3275802]), 43)),
>      ((array([-0.41990178,  1.01312245]), 2),
>       (array([ 0.06196598,  1.88883008]), 40)),
>      ((array([-0.41990178,  1.01312245]), 2),
>       (array([ 1.08164892,  0.47925854]), 41)),
>      ((array([-0.41990178,  1.01312245]), 2),
>       (array([-0.4764733 ,  0.84099526]), 42)),
>      ((array([-0.41990178,  1.01312245]), 2),
>       (array([-0.7503309,  0.3275802]), 43)),
>      ((array([ 1.74195034,  0.59257843]), 1),
>       (array([ 0.62945922, -0.39004683]), 44)),
>      ((array([ 1.74195034,  0.59257843]), 1),
>       (array([ 0.40821631, -0.64437056]), 45)),
>      ((array([ 1.74195034,  0.59257843]), 1),
>       (array([-0.21032356,  0.19358758]), 46)),
>      ((array([ 1.74195034,  0.59257843]), 1),
>       (array([ 0.82872034,  0.34594806]), 47)),
>      ((array([ 1.74195034,  0.59257843]), 1),
>       (array([ 1.84918398,  1.06022452]), 48)),
>      ((array([ 1.74195034,  0.59257843]), 1),
>       (array([ 1.19255377,  1.24440407]), 49)),
>      ((array([-0.41990178,  1.01312245]), 2),
>       (array([ 0.62945922, -0.39004683]), 44)),
>      ((array([-0.41990178,  1.01312245]), 2),
>       (array([ 0.40821631, -0.64437056]), 45)),
>      ((array([-0.41990178,  1.01312245]), 2),
>       (array([-0.21032356,  0.19358758]), 46)),
>      ((array([-0.41990178,  1.01312245]), 2),
>       (array([ 0.82872034,  0.34594806]), 47)),
>      ((array([-0.41990178,  1.01312245]), 2),
>       (array([ 1.84918398,  1.06022452]), 48)),
>      ((array([-0.41990178,  1.01312245]), 2),
>       (array([ 1.19255377,  1.24440407]), 49)),
>      ((array([ 1.44728983,  0.37634892]), 3),
>       (array([-0.40769019,  0.26518391]), 37)),
>      ((array([ 0.44497839,  0.29831191]), 4),
>       (array([-0.40769019,  0.26518391]), 37)),
>      ((array([-0.51318497, -0.20029463]), 5),
>       (array([-0.40769019,  0.26518391]), 37)),
>      ((array([-0.27315507,  0.57827367]), 6),
>       (array([-0.40769019,  0.26518391]), 37)),
>      ((array([ 1.44728983,  0.37634892]), 3),
>       (array([ 0.29609466,  1.2370943 ]), 38)),
>      ((array([ 1.44728983,  0.37634892]), 3),
>       (array([-0.65231655, -0.36407806]), 39)),
>      ((array([ 0.44497839,  0.29831191]), 4),
>       (array([ 0.29609466,  1.2370943 ]), 38)),
>      ((array([ 0.44497839,  0.29831191]), 4),
>       (array([-0.65231655, -0.36407806]), 39)),
>      ((array([-0.51318497, -0.20029463]), 5),
>       (array([ 0.29609466,  1.2370943 ]), 38)),
>      ((array([-0.51318497, -0.20029463]), 5),
>       (array([-0.65231655, -0.36407806]), 39)),
>      ((array([-0.27315507,  0.57827367]), 6),
>       (array([ 0.29609466,  1.2370943 ]), 38)),
>      ((array([-0.27315507,  0.57827367]), 6),
>       (array([-0.65231655, -0.36407806]), 39)),
>      ((array([ 1.44728983,  0.37634892]), 3),
>       (array([ 0.06196598,  1.88883008]), 40)),
>      ((array([ 1.44728983,  0.37634892]), 3),
>       (array([ 1.08164892,  0.47925854]), 41)),
>      ((array([ 1.44728983,  0.37634892]), 3),
>       (array([-0.4764733 ,  0.84099526]), 42)),
>      ((array([ 1.44728983,  0.37634892]), 3),
>       (array([-0.7503309,  0.3275802]), 43)),
>      ((array([ 0.44497839,  0.29831191]), 4),
>       (array([ 0.06196598,  1.88883008]), 40)),
>      ((array([ 0.44497839,  0.29831191]), 4),
>       (array([ 1.08164892,  0.47925854]), 41)),
>      ((array([ 0.44497839,  0.29831191]), 4),
>       (array([-0.4764733 ,  0.84099526]), 42)),
>      ((array([ 0.44497839,  0.29831191]), 4),
>       (array([-0.7503309,  0.3275802]), 43)),
>      ((array([-0.51318497, -0.20029463]), 5),
>       (array([ 0.06196598,  1.88883008]), 40)),
>      ((array([-0.51318497, -0.20029463]), 5),
>       (array([ 1.08164892,  0.47925854]), 41)),
>      ((array([-0.51318497, -0.20029463]), 5),
>       (array([-0.4764733 ,  0.84099526]), 42)),
>      ((array([-0.51318497, -0.20029463]), 5),
>       (array([-0.7503309,  0.3275802]), 43)),
>      ((array([-0.27315507,  0.57827367]), 6),
>       (array([ 0.06196598,  1.88883008]), 40)),
>      ((array([-0.27315507,  0.57827367]), 6),
>       (array([ 1.08164892,  0.47925854]), 41)),
>      ((array([-0.27315507,  0.57827367]), 6),
>       (array([-0.4764733 ,  0.84099526]), 42)),
>      ((array([-0.27315507,  0.57827367]), 6),
>       (array([-0.7503309,  0.3275802]), 43)),
>      ((array([ 1.44728983,  0.37634892]), 3),
>       (array([ 0.62945922, -0.39004683]), 44)),
>      ((array([ 1.44728983,  0.37634892]), 3),
>       (array([ 0.40821631, -0.64437056]), 45)),
>      ((array([ 1.44728983,  0.37634892]), 3),
>       (array([-0.21032356,  0.19358758]), 46)),
>      ((array([ 1.44728983,  0.37634892]), 3),
>       (array([ 0.82872034,  0.34594806]), 47)),
>      ((array([ 1.44728983,  0.37634892]), 3),
>       (array([ 1.84918398,  1.06022452]), 48)),
>      ((array([ 1.44728983,  0.37634892]), 3),
>       (array([ 1.19255377,  1.24440407]), 49)),
>      ((array([ 0.44497839,  0.29831191]), 4),
>       (array([ 0.62945922, -0.39004683]), 44)),
>      ((array([ 0.44497839,  0.29831191]), 4),
>       (array([ 0.40821631, -0.64437056]), 45)),
>      ...]

In [ ]:
def compute_dst_sq(): # (N, M)
  # dst[n, m] = |x_n - x'_m|^2
  dst = train_data.cartesian(test_data)
  dst = np.zeros((N, M))
  for i in range(N):
    for j in range(M):
      tmp = train_data[i, :] - test_data[j, :]
      dst[i, j] = np.sum(tmp * tmp)
  return dst

def compute_pu(data): # (data.N, T)
  # pu[n, t] = <data_n, ray_t>
  return np.dot(data, rays.T)

dst = compute_dst_sq()
pu_train = compute_pu(train_data)
pu_test = compute_pu(test_data)

In [ ]:
def compute_ray_lengths(): # (M, T)
  lengths = np.zeros((M, T, N))
  # lengths[m, t, n] = dst[n, m] / (2 * (pu_train[n, t] - pu_test[m, t]))
  for n in range(N):
    for m in range(M):
      lengths[m, :, n] = dst[n, m] / (2 * (pu_train[n, :] - pu_test[m, :]))
      
  lengths[lengths < 0] = np.inf
  
  if one_vs_all:
    for n in range(N):
      lengths[n, :, n] = np.inf

  lengths = np.min(lengths, axis=2)
  # lengths = np.sort(lengths, axis=1) # not currently needed
  return lengths

lengths = compute_ray_lengths()

In [ ]:
def _old_compute_integrals(): # (M)
  integrals = np.zeros((M,))
  for m in range(M):
    current = 0.
    cur_coeff = 0.
    cur_T = np.sum(lengths[m, :] < np.inf)
    prev_len = 0.
    
    for t in range(cur_T):
      cur_len = lengths[m, t]
      current += (cur_len - prev_len) * (cur_T - t)
      if t > 0:  # can omit with large D
        current += cur_coeff * (-D + 1) * (np.power(cur_len, -D + 1) - np.power(prev_len, -D + 1))
      cur_coeff += np.power(cur_len, D)
      prev_len = cur_len
    
    integrals[m] = current
  return integrals

def compute_integrals(): # (M)
  integrals = np.zeros((M,))
  finite = np.sum(np.isfinite(lengths), axis=1)
  lengths[np.isinf(lengths)] = 0
  integrals = np.sum(lengths, axis=1) / finite
  return integrals

integrals = compute_integrals()

In [ ]:
integrals

In [ ]:
weights = 1. / integrals
weights = (50. / np.max(weights)) * weights

In [ ]:
fig = plt.figure()
plt.scatter(test_data[:, 0], test_data[:, 1], weights)
display(fig)

In [ ]:
from sklearn.neighbors.kde import KernelDensity
kde = KernelDensity(kernel='tophat', bandwidth=0.13).fit(train_data)
kde_weights = kde.score_samples(test_data)
kde_weights = np.exp(kde_weights)
kde_weights = (50. / np.max(kde_weights)) * kde_weights

In [ ]:
fig = plt.figure()
plt.scatter(test_data[:, 0], test_data[:, 1], kde_weights)
display(fig)